version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: webforge
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: builder
  backend:
    build: ./apps/backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build: ./apps/frontend
    ports:
      - "3000:3000"
